
name: Deployment1

on:
  push:
    branches: [development , main ] 
jobs:
  
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm i -f

      - name: Buid the application
        run: npm run build

  Deploy:

    needs : Build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to  Development
        if: github.ref == 'refs/heads/development'
        env:
          PRIVATE_KEY: ${{ secrets.ATL2_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.ATL2_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{secrets.ATL2_HOSTNAME}} '
            cd /home/ubuntu/aim_be &&
            sudo git pull origin development &&
            npm run build && pm2 stop all && pm2 delete all && npm run start:prod && pm2 save -f'
      - name: Deploy to PROD Env
        if: github.ref == 'refs/heads/main'
        env:
          PRIVATE_KEY: ${{ secrets.ATL2_STG_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.ATL2_STG_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{secrets.ATL2_STG_HOSTNAME}} '
            cd aim2.0_be &&
            sudo git pull origin main &&
            npm run build && pm2 stop all && pm2 delete all && npm run start:prod && pm2 save -f'

            


            

      
  
